version: '3'
services:
  eureka:
#    image: aradocker/demo-eureka
    networks:
      - web
    ports:
    - 8761:8761
    build:
      context: _eureka
      dockerfile: Dockerfile
  vue-service:
#    image: aradocker/demo-spring-vue
    ports:
    - 8080:8080
    networks:
      - web
    build:
      context: __modules/__vue
      dockerfile: Dockerfile
  sample-rest:
#    image: aradocker/demo-sample-rest
    ports:
    - 8000:8000
    networks:
      - web
    depends_on:
      - eureka
    build:
      context: __modules/__sample
      dockerfile: Dockerfile

networks:
  web: